title: Informavore
baseURL: "https://informavo.re/"
theme: papyrus
languageCode: zh-CN
paginate: 7

enableRobotsTXT: true
enableEmoji: true

params:
  env: production
  description: "Information is like a wind, always by my side."
  keywords: [Blog, Portfolio]
  author: Shyrz
  images:
    - banner.png
  favicon: favicon.svg
  logo:
    icon: images/logo.svg
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: true

  # label:
  #   text: "Informavore"
  #   icon: logotype.png
  #   iconHeight: 35

  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:
    - posts
    - notes

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: true
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: hello@informavo.re

  socialIcons:
    - name: gmail
      url: email
    - name: twitter-simple
      url: "https://twitter.com/shyrz__"
    - name: telegram-simple
      url: "https://t.me/informavore_channel"
    - name: github-simple
      url: "https://github.com/shyrz"
    - name: rss-simple
      url: "feed.xml"
    

  socialAccounts:
    twitter:
      username: shyrz__

  homeInfoParams:
    Title: "▲ 信息动物"
    Content: |
      欢迎来到信息动物 Informavore
      
      - 本站点为 Shyrz 的 Obsidian 仓库生成的发布
      
      - 主题采用的是 [Papyrus](https://github.com/shyrz/hugo-papyrus)，基于 [Reorx](https://reorx.com) 的 [PaperModX](https://github.com/reorx/hugo-PaperModX) 开发

      - 当前尚存在诸多不完善之处，将在今后逐步修正

  commentSystems:
   disqus:
     shortname: shyrz
   remark42:
     url: https://remark.materium.io
     site: shyrz.github.io
   telegramWidget:
     channel: informavore_channel
     accentColor: "9077e1"
     limit: 20
  defaultCommentSystems:
   remark42: true

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Newsletter
      url: /newsletter/
      weight: 3
    - name: Archives
      url: /archives/
      weight: 4

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
